### ISSUE TITLE
how I use with @ngrx?

### ISSUE THREAD

**Issue by mailok** [pelotom/unionize#10]
I tried to use but, I do not know how to do to reducer funcion. In the example of the readme, it defines a const variable, but in @ngrx, needed a funcion

**Comment by pelotom** [comment]
Can you give an example of what you’re tryin to do? I’m not sure what the question is.

**Comment by mailok** [comment]
I just test and it works great!!!, It is super cool. Congratulations for good work.

**Comment by pelotom** [comment]
Great, good to hear!
