### ISSUE TITLE
How to define Action without payload?

### ISSUE THREAD

**Issue by mailok** [pelotom/unionize#11]
How to define Action Without payload?

I have actions with payload and without payload In my definition.
With payload is:  ADD_TODO: ofType<{ id: string; text: string }>()

but without How is it?

I tried this: CLEAN: ofType<{}>() but the compiler show error when call store.dispatch(Action.CLEAN())
It works, but the compiler shows me error.
What is the right way?

**Comment by pelotom** [comment]
@mailok unfortunately this is a limitation of the type system. No-payload actions have to be given empty payloads, i.e. `Action.CLEAN({})`.

**Comment by mailok** [comment]
Well, no matter, still great use this library.
I have another question, I somehow can define the type of actions this: [TASK] ADD_TODO to differentiate actions in DevTools in de chrome.

**Comment by pelotom** [comment]
Hm, I'm not sure what you're asking?

**Comment by mailok** [comment]
![captura](https://user-images.githubusercontent.com/3769277/31898835-1b87c6c6-b7e8-11e7-8cd0-5fc705655782.PNG)

In the picture, show some action, the acction ADD_TODO and CLEAN are actions using unionize, the others action you see  are actions in the traditional way, The difference is that the traditional way, You can specify the feature to which they belong, for exaple the acction [Stats] Add Updating Stage, belong the feature Stats, I would like to do the same with actions of unionize, can put on your type some like that: [TASK] ADD_TODO

**Comment by pelotom** [comment]
You mean changing the action name to have non-identifier characters? You can use a string index signature like so:

```ts
const Actions = unionize({
  '[TASK] ADD_TODO': ofType<{ id: string; text: string }>(),
  // ...
});

const addTodo = Actions['[TASK] ADD_TODO']({ id: 'hello', text: 'world' });
```

but that's obviously going to be more painful to work with. In TypeScript 2.6 you should be able to do this:

```ts
const ADD_TODO = '[TASK] ADD_TODO'
const CLEAN = '[TASK] CLEAN'

const Actions = unionize({
  [ADD_TODO]: ofType<{ id: string; text: string }>(),
  [CLEAN]: ofType<{}>(),
})

const addTodo = Actions[ADD_TODO]({ id: 'hello', text: 'world' })
```

**Comment by mailok** [comment]
I get it. Thank you
