### ISSUE TITLE
A question about Type predicates

### ISSUE THREAD

**Issue by mailok** [pelotom/unionize#12]
In the traditional way, in the effects, it's used actions$.ofType(), In your proposal 
action$.filter(Action.is.TOGGLE_TODO). my question is, your proposal does the same?  It is faster than the traditional way?

**Comment by pelotom** [comment]
It is the same in terms of runtime efficiency and semantics. The difference is that the typing is more accurate:

```ts
action$.ofType('TOGGLE_TODO')
  .mergeMap(action =>
    // here, action is still has the basic generic type; it doesn't reflect
    // the fact that you've narrowed the action's type to TOGGLE_TODO
  )
```

```ts
action$.filter(Action.is.TOGGLE_TODO)
  .mergeMap(action =>
    // here the action has the correct type, you can access fields that are specific
    // to TOGGLE_TODO in a type-safe way
  )
```
