### ISSUE TITLE
Creating subsets from existing unions

### ISSUE THREAD

**Issue by OliverJAsh** [pelotom/unionize#16]
Is it possible to create a subset union type from an existing union type?

E.g. given `type Foo = A | B | C | D`, I want to create another union that is just composed of `A | B`.

Perhaps this is a bad idea and I'm looking at this the wrong way. For context, here is why I think I need this.

I have this union:

``` ts
const PropertyComparison = unionize({
    Same: ofType<{}>(),
    SimilarFunctions: ofType<{}>(),
    ValuesDeepEqual: ofType<{}>(),
    Unequal: ofType<PropertyComparisonUnequal>(),
});
type PropertyComparison = typeof PropertyComparison._Union;
```

And this record type:

``` ts
type PropertiesComparison = { [key: string]: PropertyComparison };
```

Now I also want to create a type like `PropertiesComparison` except where the values can only be `ValuesDeepEqual | SimilarFunctions`:

``` ts
type PropertyComparisonSubset = PropertyComparison.ValuesDeepEqual | PropertyComparison.SimilarFunctions;
type PropertiesComparisonSubset = { [key: string]: PropertyComparisonSubset };
```

**Comment by pelotom** [comment]
You could define `PropertyComparisonSubset` first:

```ts
const PropertyComparisonSubset = unionize({
  SimilarFunctions: ofType<{}>(),
  ValuesDeepEqual: ofType<{}>(),
});
```

and then use it in the definition of `PropertyComparison`:

```ts
const PropertyComparison = unionize({
  Same: ofType<{}>(),
  ...PropertyComparisonSubset._Record,
  Unequal: ofType<PropertyComparisonUnequal>(),
});
```

**Comment by pelotom** [comment]
@wmaurer ah, yes, it should return the `_Record` that was passed in. Happy to take a PR.

**Comment by OliverJAsh** [comment]
Unfortunately this workaround doesn't help when you want to create multiple (potentially overlapping) subsets, e.g.:

``` ts
type LikesCheese = Bob | Sarah;
type IsOld = Sarah;
type All = Bob | Sarah | Sam;
```

**Comment by OliverJAsh** [comment]
I find myself needing this again and again. As I mentioned in my previous comment, the workaround mentioned doesn't help, because there can be many overlapping subsets.

It would be really useful to be able to create an existing unionize union and "pick" from it, which would create a new unionize union (type, `match`, et al).

**Comment by wmaurer** [comment]
@OliverJAsh 
The Record that you pass to `unionize` (and what you get back via the `_Record` property is simply just an object literal. You can destructure it as you like or use something like Ramda's pick to take what you like and then spread the results into another object literal that you can pass to unionize.
It probably wouldn't take much to create an abstraction that works neatly for your use case.

But I could see problems combining existing unionize unions - e.g. what if they had differring `tag` or `value` props?

**Comment by OliverJAsh** [comment]
Hmm, but if we do that, I don't understand how it's possible to match a subset union. Using my example above:

``` ts
type All = Bob | Sarah | Sam;

type LikesCheese = Pick<All, 'Bob' | 'Sarah'>
type IsOld = Pick<All, 'Sarah'>;
```

How would we define a function that checks whether an `All` instance is a `LikesCheese`? We would probably have to write one manually 🤔

**Comment by pelotom** [comment]
Something like this?

```ts
// from lodash, ramda or whatever
declare function pick<O, K extends keyof O>(o: O, ...keys: K[]): Pick<O, K>;

const All = unionize({ Bob: {}, Sarah: {}, Sam: {} });
type All = UnionOf<typeof All>;

const LikesCheese = unionize(pick(All, 'Bob', 'Sarah'));
type LikesCheese = UnionOf<typeof LikesCheese>;

// maybeLikesCheese: (all: All) => LikesCheese | null
const maybeLikesCheese = All.match({
  ...LikesCheese,
  default: () => null
});
```

**Comment by OliverJAsh** [comment]
Interesting. I just tried that but ran into this problem:

``` ts
import unionize, { ofType, UnionOf } from 'unionize';

declare function pick<O, K extends keyof O>(o: O, ...keys: K[]): Pick<O, K>;

const All = unionize({ Bob: ofType<{ name: string }>() });
type All = UnionOf<typeof All>;

const LikesCheese = unionize(pick(All, 'Bob'));
type LikesCheese = UnionOf<typeof LikesCheese>;

// Expected: (value: { name: string }) =>
// Actual: (value?: {} | undefined) =>
LikesCheese.Bob;
```
