### ISSUE TITLE
Suggestion on inline usage, updates, simple records and "_" prop as a default

### ISSUE THREAD

**Issue by twop** [pelotom/unionize#18]
I started to use unionize at work for modelling redux states. So far it is a great conceptual fit however we miss several features/syntax :)

Usually it looks similar to this.
```typescript
const State = unionize({
  Loading: ofType<{}>(), // note there is no payload
  Loaded: ofType<{ data: string }>(),
  Error: ofType<{ err: string }>()
});
```
### Pattern matching
So far we have way more inline usage of matching (when there is an object to match with right away).
default syntax is a bit verbose  ()=>{...}
payload for default case is not the initial object (useful for updates)

Suggestion

```typescript
const val = State.Loaded({ data: 'some data' });
const str = State.match(val, { // note that val is a fist arg here
  Loaded: ({ data }) => data,
  _: v => 'default' // default, v === val here
});
```
"_" is a reserved prop for default case. Which is aligned with other languages + probably won't be used (vs "def" or "default")

#### In summary
- "\_" is a fallback case + the original object is passed as payload so it is possible to write {_:identity} where identity = x=>x 

- inline usage vs curried. Maybe another func name: matchInl, matchI or even switch :)

### First class support for no payload cases
```typescript
const State = unionize({
  Loading: simple(), // need a better name though, "noArgs" maybe?
  Loaded: ofType<{ data: string }>(),
  Error: ofType<{ err: string }>()
});

const loading = State.Loading(); // note no args to create it.
//So it can even be memoized (return the same object all the time)
```

### Immutable update
this comes up a lot with dealing with redux. I need to modify data only if state is loaded.
```typescript
const updatedVal = State.update(val, {
  Loaded: ({ data }) => ({ data: data + ' yay!' })
});
```
Note: 

- update signature:
update:: State -> State.
- If Loaded case would have a different shape ofType<{data: string, count: number}> nothing would change. So Loaded case has a signature of 
Loaded:: Loaded -> Partial Loaded (similar to react's "setState").
- There is no need to provide Error and Loading cases. The same value is returned if there is no match.
Functionally will be similar to prism.

### config object as an argument
I know that in ur example it was used to represent redux actions but writing
```typescript
const Action = unionize({
  ADD_TODO:  ofType<{ id: string; text: string }>(),
}, 'type', 'payload');

const action = Action.ADD_TODO({...})
```
is a bit tedious.

suggestion
```typescript
const Todos = unionize(
  { Add: ofType<{ id: string; text: string }>() },
  { tag: 'type', payload: 'payload', prefix: '[TODOS] ' }
);

type Config = { tag?: string; payload?: string; prefix?: string };

//so you can simplify creating new actions
const namespace = (prefix: string) => ({ tag: 'type', payload: 'payload', prefix })

const Todos = unionize(
  { Add: ofType<{ id: string; text: string }>() },
  namespace( '[TODOS] ')
);

type AddType = typeof Todos._Record.Add
// {tag: "[TODOS] Add", payload: {id: string; text: string}}
```

I know this is a lot of suggestions but I decided to reach out to see if they make sense to you :)

And thanks for an amazing library!

**Comment by pelotom** [comment]
> ### Pattern matching
> So far we have way more inline usage of matching (when there is an object to match with right away).
> default syntax is a bit verbose  ()=>{...}

I would be open to adding an overload that lets you pass the object to be matched first. I do find lots of uses for passing the curried match function to a HOF though, so I definitely want to keep that as an option.

> payload for default case is not the initial object (useful for updates)

I guess I don't see any harm in adding this. I usually feel like it's a bit superfluous to pass someone an object they already clearly have in their possession, since they passed it to _you_, but I can see that it's useful if you're passing an expression to the match function.

> Suggestion
> 
> ```typescript
> const val = State.Loaded({ data: 'some data' });
> const str = State.match(val, { // note that val is a fist arg here
>   Loaded: ({ data }) => data,
>   _: v => 'default' // default, v === val here
> });
> ```
> "_" is a reserved prop for default case. Which is aligned with other languages + probably won't be used (vs "def" or "default")

I normally shy away from reserving words, but I think this is fine, and would make it easier to disambiguate the overloads due to the first suggestion. Although I'd probably opt for `default` instead of `_`.

> ### First class support for no payload cases
> ```typescript
> const State = unionize({
>   Loading: simple(), // need a better name though, "noArgs" maybe?
>   Loaded: ofType<{ data: string }>(),
>   Error: ofType<{ err: string }>()
> });
> ```

I would just use `Loading: {}`, why does it need to be more complicated? In the case of "unit" types, there's no need to use the fakery of `ofType<...>()`, you can just provide a literal value of the type.

> ```
> const loading = State.Loading(); // note no args to create it.
> //So it can even be memoized (return the same object all the time)
> ```

There was [a PR](https://github.com/pelotom/unionize/pull/15) to accomplish this but it was deferred until 2.8 lands.

> ### Immutable update
> ...

I really like it! 👍

> ### config object as an argument
> ...

Also like it!

> I know this is a lot of suggestions but I decided to reach out to see if they make sense to you :)
> 
> And thanks for an amazing library!

Thanks for the suggestions, I think there are a lot of good ideas here. I'm quite busy at the moment so I can't promise when I'll have time to get to them, but I would certainly entertain PRs 😄

**Comment by twop** [comment]
I actually was going to start working on "my own version" today.. started to get hopeless :)
But if you agree with the spirit of the proposals above I would be happy to contribute!

I would want to be aligned on api surface first though.
Questions that came to my mind:

1. For inline matching do we use a different keyword? "switch" jumps to my mind (I wanted to name my lib something like "ts-enum" and model it after swift's enum). If we use just "match" is it going to be hard to determine at runtime (I'm not in expert in ts)? Does this magic involve checking how many args were passed in?

2. btw I like "Loading:{}" for simple cases. This one has to wait ts 2.8 right?

3. Immutable update should be curried or inline? Or both? If both the first question applies here as well (At work I need inline). + There is an alternative syntax for that:
```typescript
const updatedVal = State.update(val, {
  Loaded: ({ data }) => ({ data: data + ' yay!' })
});
// vs
const updatedVal = State.upd.Loaded(val, ({ data }) => ({ data: data + ' yay!' }));
// So accept any of the states but execute update only in Loaded case
```
I personally feel that the first one is more generic and intuitive but still wanted to bring that up.

4. Config object is potentially a breaking change. It should easy to create an overload though string vs object arguments (again not an expert in ts). 

If all 3 make sense to you (except 2) would you rather have them as a single PR or 3 separate ones?

**Comment by twop** [comment]
Awesome!

I will make a PR for 1.1 first and see where to go next (or at least try my best). I guess config object should be bundled for a new npm package because of breaking changes. But can be done as a separate PR I suppose.

+ for "Loading:{}" I meant that I want the "State.Loading()" with no args. I feel that for "{}" we can memoize the object as well (not for ofType<{}> though). Also I feel I like more "Loading()" vs "Loading" just to be aligned with other cases to reduce cognitive overload.

**Comment by twop** [comment]
I partially implemented 4 here: https://github.com/twop/unionize/tree/config-object
The problem with prefix is I cannot make a literal out of two literal sum:
```typescript
const a = 'a'; // typeof a = 'a'
const b = 'b'; // typeof b = 'b'
const ab = a + b; // typeof ab = string.
```

So as far as I understand the initial goal is not achievable 
```typescript
const Todos = unionize(
  { Add: ofType<{ id: string; text: string }>() },
  { tag: 'type', payload: 'payload', prefix: '[TODOS] ' }
);

type AddType = typeof Todos._Record.Add
// {tag: "[TODOS] Add", payload: {id: string; text: string}}
// instead it would be {tag: string, ...}
```
Am I missing something? regardless I think an object is still a better api for configuration + I was able to preserve typings regarding MultiValueVariants and SingleValueVariants

**Comment by twop** [comment]
Implemented update feature

https://github.com/twop/unionize/tree/update-func

One big concern that I have is excessive usage of "any". I was thinking of ways of getting rid of that but none come to mind prior 2.8.

I also added typings and tests for the feature. If you do like the changes this branch has all the features combined.

**Comment by twop** [comment]
I was thinking of applying my knowledge working on unionize and make an array based impl.
aka ['One', string] | ['Two', number, string]
I implemented draft typings for it and it looks promising: 
https://gist.github.com/twop/a0a8051f04fa4e979154d5f9ee09435e

It would be possible to model redux state based on it but not redux action.

**Comment by twop** [comment]
Thanks!
