### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by twop** [pelotom/unionize#27]
Eager to use it at work :)

**Comment by pelotom** [comment]
Sorry, I have at least one other breaking change I'm considering putting in before going to v2. I can make a preview release though.

**Comment by twop** [comment]
If you don't mind me asking what is that breaking change?

**Comment by pelotom** [comment]
Reviving #15.

**Comment by twop** [comment]
something like that
```ts
export type CreatorFunc<T, R> = T extends NoData
 ? () => R
: T extends ofType<infer A> ? (a: A)=> R 
: never
```

**Comment by pelotom** [comment]
So are you opposed to making this part of the next release because you can't upgrade TypeScript at work yet?

**Comment by twop** [comment]
Not like i'm opposed. But it might be too much hassle to migrate all at once (if you include ts 2.8) for your lib consumers (this is just FYI). I'm planning to migrate next monthish (don't wanna do it before a milestone).

**Comment by twop** [comment]
Also with ts 2.8 you can do way richer things. Take a look: 
```ts
export type Types = {
  (): NoData;
  <T>(): One<T>;
  <T>(val: T): Const<T>;
  <T1, T2>(): Two<T1, T2>;
  <T1, T2, T3>(): Three<T1, T2, T3>;
};

//this is the same helper as ofType<T>
export const t: Types = ((val: any) => val) as any;

//then the type system can be richer
const U = Union({
  Simple: t(), // no payload
  One: t<string>(), // one argument
  Const: t(3), // one constant argument that is baked in
  Two: t<string, number>(), // two arguments
  Three: t<string, number, boolean>() // three
});
```
Not like `unionize` directly needs it now. But just wanted to share what is possible

**Comment by pelotom** [comment]
Yeah, I'm keenly aware of 2.8's superpowers and anxious to use them 😄

**Comment by twop** [comment]
Overall I guess it makes sense to bundle it. + maybe provide a shorter alias for ofType?
like `t`. and the empty of is either t(), {}, of ofType<void>() etc.

**Comment by twop** [comment]
I can make a PR for that :)

**Comment by pelotom** [comment]
> Overall I guess it makes sense to bundle it. + maybe provide a shorter alias for ofType?
> like `t`. and the 'empty' can be  one of `t()`, `{}`, ofType<`void`>() etc. Is ofType can coexist with t?.
> 
> What I'm getting at is to type `ofType<void>()` is a bit verbose but just `ofType()` is a bit weird (what type?!). IMHO `t()`, `t<string>()` is more expressive.

I'm not really a fan of exporting a variable named just `t`. A top-level exported name should minimally give some indication of what its semantics are. You can always use renaming imports as a consumer of the library:

```ts
import { unionize, ofType as t } from 'unionize';
```

**Comment by twop** [comment]
Makes sense. How would you prefer to define empty payload then?

I tried to express exactly empty object but failed.

```ts
const emp = {}
type Empty = typeof emp

function f<T>():
    T extends Empty ? 'empty'
    : T extends void ? 'void'
    : T extends null ? 'null'
    : T extends undefined ? 'und'
    : T extends object ? 'obj'
    : T extends string ? 'str' 
    : T extends number ? 'num'  
    : never { return undefined as any }


const empty = f<{}>(); //empty
const vo = f<void>(); // void
const nu = f<null>(); // empty | void | ... cannot infer
const obj = f<{a: 1}>(); //nope. empty
const und = f<undefined>(); // empty 
const str = f<string>();
```

it seems that the only reliable way to type it is `ofType<void>()`. Which looks reasonable.

PS. sry for my arrogance about ts features. I'm just super excited about them :)

**Comment by pelotom** [comment]
> I tried to express exactly empty object but failed.

Did you have `strictNullChecks` enabled? I get

```ts
const empty = f<{}>(); //empty
const vo = f<void>(); // void
const nu = f<null>(); // null 
const obj = f<{a: 1}>(); // obj
const und = f<undefined>(); // void 
const str = f<string>(); // str
```

I think the test you want for the type that excludes everything but `{}` is `T extends { [key: string]: never }`.

>PS. sry for my arrogance about ts features. I'm just super excited about them :)

No worries, understandable!

**Comment by twop** [comment]
I tried that using ts playground (didn't check the flag). If it works that's awesome!
Which means that `{}`, `ofType<void>()`, `ofType<{}>()` should probably just work!

**Comment by pelotom** [comment]
BTW, see #28 for another breaking change I was contemplating before v2. Feedback welcome!
