### ISSUE TITLE
Proposal: restore old API of creating union via type parameter

### ISSUE THREAD

**Issue by pelotom** [pelotom/unionize#28]
While we're making breaking changes for 2.0, I've been thinking about ways we could return to the simpler original API of Unionize. It used to be that the `unionize` function used a type parameter instead of an actual object to specify the mapping of tags to values:

```ts
const Action = unionize<{
  ADD_TODO: { id: string; text: string }
  SET_VISIBILITY_FILTER: 'SHOW_ALL' | 'SHOW_ACTIVE' | 'SHOW_COMPLETED'
  TOGGLE_TODO: { id: string }
}>('type', 'payload')
```

Simple and clean!

The magic that powered this was ES6 `Proxy`s; unfortunately [it was pointed out](https://github.com/pelotom/unionize/issues/3) that proxies carried an enormous performance penalty, and thus we ended up with the current API involving `ofType` with its impossible signature of `<A>() => A`. It works and is efficient, but it's unsightly and unsafe.

How could we get back to something like what we had originally, but without using `Proxy`? Well, we only needed it to trap property accesses in support of the creation, `is` and `as` functions:

```ts
Action.ADD_TODO({ id: 'abc', text: 'hello world' });
Action.is.ADD_TODO(obj);
Action.as.ADD_TODO(obj);
```

But we could alternatively make these functions which take a tag argument:

```ts
Action.create('ADD_TODO', { id: 'abc', text: 'hello world' });
Action.is('ADD_TODO', obj);
Action.as('ADD_TODO', obj);
```

There could be curried versions of these as well, so that

```ts
Action.create('ADD_TODO'); // returns a creation function
Action.is('ADD_TODO'); // returns a type guard
Action.as('ADD_TODO'); // returns a casting function
```

_Slightly_ more verbose, but not much. The more I think about it, the more this tradeoff seems worth it to leave `ofType` behind.

**Comment by twop** [comment]
I would say it doesn't improve ergonomics that much in comparison to 
```ts
type Action:
  | {type: 'ADD_TODO', payload: { id: string; text: string }}
  | {type: 'SET_VISIBILITY_FILTER':  payload: 'SHOW_ALL' | 'SHOW_ACTIVE' | 'SHOW_COMPLETED'}
  ....
```
For me personally type ctors is a big deal. I would say I would take a bullet and use ofType<>() once and enjoy the benefits throughout the many placed. So my take on this topic: it makes sense to optimize for usage rather than declaration. So I would use `unionize` if you replace 'ofType' with `desiredDataShape` :)

**Comment by twop** [comment]
So I do want to have an artifact of union declaration for usage ergonomics (namely type ctors). 
I guess there is a universe where it can be achieved with something like:
```ts
const Action = uninonize( 
    {tag: 'type', value: payload},
    Case('ADD_TODO').of<{ id: string; text: string }>(),
    Case('NO_PAYLOAD'));
```
But I'm not a huge fan of this approach.

**Comment by pelotom** [comment]
My reasoning is
1. It's much cleaner and more readable at the declaration site, which has some value for documentation, and is easier to learn.
2. There's only one thing to import, so it could be
  ```ts
  import unionize from 'unionize';
  ```
  and that's all anyone needs to use the library.
3. Coming from Haskell I'm allergic to signatures like `<A>() => A` 😄
4. I think it's only microscopically more inconvenient to use at the usage site. Autocomplete works just as well filling out string literals as it does object properties.

**Comment by pelotom** [comment]
>For me personally type ctors is a big deal.

What do you mean by type ctors exactly?

**Comment by twop** [comment]
Wow. You probably do miss type classes then :)

I mean 
```ts
const Action = unionize({Add: ofType<{..}>, Complete: ofType<{..}>()})
 // usually do that in reducers and React components
const {Add, Complete} = Action;

const learnHaskell = Add({id: '1331', text:'Learn Haskell'}); // this one I call ctor.
```

**Comment by twop** [comment]
I was thinking about your proposal and usage of proxy. So here is a snippet: 
```ts
const Action = unionize<{
  Add: { id: string; text: string };
  Complete: { id: string };
}>({ tag: 'type', value: 'payload' });

// no proxy objects, probably no currying either. But everything is typechecked
const add = Action.create('Add', {
  id: 'vds23',
  text: 'Learn Haskell'
});

// imho it is better to be explicit about proxy.
const { Add, Complete } = Action.proxyCreators;

// Complete is just a normal function. 
const complete = Complete({ id: 'vds23' });
// a shortcut for Action.create('Complete', { id: 'vds23' })

// match & transform can be the same right?
Action.match({
  Add: ({ text }) => text,
  default: _ => 'something else'
});
```
I'm not 100% sure if it is a better api. But definitely makes sense to me.

I think it is conceptually similar to:
https://medium.com/@bterlson/strongly-typed-event-emitters-2c2345801de8
https://github.com/bterlson/strict-event-emitter-types

**Comment by pelotom** [comment]
Yep, that’s all pretty much what I had in mind. I think I’d still want to call if just `creators`, the docs can be explicit about the fact that it’s implemented with `Proxy`.

**Comment by twop** [comment]
I guess it makes sense to provide a draft impl for proxy. 
```ts
const creatorsProxy = {
  // note you can even momoize it.
  get: (union, tag) => (payload)=> ({
    union.create(tag, payload)
  })
};

const unionObj = {...} // result of unionize

// add creators
unionObj.creators = new Proxy(unionObj, creatorsProxy);
```

So you pay the price for `Proxy` only once when you destructure `creators`. So usually once per file or even less.

That being said, I think `ofType<void>()` is good enough. But it worth pointing out the the original api had a clearer declaration semantics :) Also `Proxy` cost is virtually nonexistent.

**Comment by pelotom** [comment]
Based on sample size = 3, this is not compelling to 2/3 users 😝Closing for now.
