### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sledorze** [pelotom/unionize#3]
Looks like going through proxies is very slow (more than two order of magnitude here).
https://jsperf.com/proxy-cost/8

..and maybe not necessary.

**Comment by pelotom** [comment]
Yeah, it's not ideal to have to use them. Any suggestions that preserve the niceties of the current API? I think we'd need to pass in the string values associated with the tags in order to iterate over them and set up the creators and predicates upfront...

**Comment by sledorze** [comment]
@pelotom yes, I think its the way to go.

**Comment by pelotom** [comment]
What about something like

```ts
unionize({
  x: value<string>(),
  y: value<number>(),
})
```

Where we pass in an object of the record type; then we can enumerate the tags, which are the properties of the object. The `value` function just a helper that returns `undefined` disguised as whatever type you provide. This is a little more verbose than the original syntax, but more DRY than requiring you to provide an array of all the keys in the record type, separate from the record itself.

**Comment by sledorze** [comment]
@pelotom Oh.. I did not see you've responded and was thiking today at it.
Yes, we need a 'value side' way to have the 'tags' (we cannot derive those from type level).
So I think it's required to have those values and capture the types (not values) of the adt params like you propose with ofType.
I don't known any other solution..

**Comment by sledorze** [comment]
@pelotom very nice, well executed!
