### ISSUE TITLE
Allow parameter-less element factory when ofType<void> is specified

### ISSUE THREAD

**Issue by mischkl** [pelotom/unionize#30]
When specifying an element with `ofType<void>`, it was my expectation that I could then use the element factory without specifying an argument, e.g. `AuthActions.LOGOUT()`. Instead it turns out I have to do `AuthActions.LOGOUT(null)` or `AuthActions.LOGOUT(undefined)`, which feels rather unnecessary. It seems to me like there should be a way to enable this behavior, by having two different types for the factory depending on whether the type is void or not.

**Comment by pelotom** [comment]
There was an abortive attempt at this with https://github.com/pelotom/unionize/pull/15 but we are definitely going to get this in for version 2, thanks for the issue!
