### ISSUE TITLE
Provide means to Simplify inferred types

### ISSUE THREAD

**Issue by sledorze** [pelotom/unionize#35]
Unionize is very useful and lean.

one can write easily such things:
```typescript
      const T = unionize({
        foo: ofType<{x : number}>(),
      });
      const input = { x: 42 };
      expect(T.foo(input).tag).toBe('foo');
```

the inferred type for `foo` is then:
```typescript
{
    tag: "foo";
} & {
    x: number;
}
```

However, as a union grows the signature start to be verbose get in the way, so one can use interface to keep things clearer.

```typescript
      interface Foo {
        x: number;
      }
      const T = unionize({
        foo: ofType<Foo>(),
      });
      const input = { x: 42 };
      expect(T.foo(input).tag).toBe('foo');
```

which generates that:
```typescript
{
    tag: "foo";
} & Foo
```

It's halfway to totally removing the boilerplate if one want to go further by doing so:

```typescript
      interface Foo {
        tag: 'foo';
        x: number;
      }
      const T = unionize({
        foo: ofType<Foo>(),
      });
      const input = { x: 42, tag: 'foo' as 'foo' };
      expect(T.foo(input).tag).toBe('foo');
```

which generates that:
```typescript
Foo
```

with (a bit) more effort we can come to this:

```typescript
      interface Foo {
        tag: 'foo';
        x: number;
      }
      const T = unionize({
        foo: ofType<Foo>(),
      });
      const input = { x: 42 };
      expect(T.foo(input).tag).toBe('foo');
```

which still generates that:
```typescript
Foo
```

I may provide a PR if interested

**Comment by pelotom** [comment]
So basically you're saying that the value types provided to `unionize` could optionally also mention the tag? That seems reasonable to me, I'd certainly entertain a PR.

**Comment by sledorze** [comment]
@pelotom let it be!

**Comment by sledorze** [comment]
PR is here: https://github.com/pelotom/unionize/pull/36
