### ISSUE TITLE
Constructors holding `Partial<T>` can be called with any argument 

### ISSUE THREAD

**Issue by geigerzaehler** [pelotom/unionize#48]
When using `Partial` as a value type the calling the constructors with any object type checks but it should not. For example the following should not type check
~~~typescript
type T = { field: string }

const U = unionize({
  PartialT: ofType<Partial<T>>(),
})

// This should fail
const u = U.PartialT({ foo: true })
const u2 = U.PartialT(true)
~~~

The underlying problems seems to be that the constraint `{} extends UnTagged<Partial<T>, 'tag'>` does not hold. If we look at the definition of `Creators` we see that this results in the constructor accepting an argument of type `undefined | {}` which seems wrong.
~~~typescript
export type Creators<Record, TaggedRecord, TagProp extends string> = {
  [T in keyof Record]: {} extends UnTagged<Record[T], TagProp>
    ? ((value?: {}) => TaggedRecord[keyof TaggedRecord])
    : ((value: UnTagged<Record[T], TagProp>) => TaggedRecord[keyof TaggedRecord])
}
~~~

I’m not sure what the solution would be but would be happy to create a PR if somebody has a suggestion.

**Comment by OliverJAsh** [comment]
I also just ran into this:

``` ts
import unionize, { ofType } from 'unionize';

type MyRecord = { src?: string; className?: string };

const myRecord: MyRecord = {
    src: 'fo',
    // Error as expected
    className: 1,
};

const MyUnion = unionize({
    MyRecord: ofType<MyRecord>(),
});

MyUnion.MyRecord({
    src: 'fo',
    // No error!!
    className: 1,
});
```

**Comment by OliverJAsh** [comment]
I can achieve the desired behaviour by making this change:

``` diff
 export declare type Creators<Record, TaggedRecord, TagProp extends string> = {
-    [T in keyof Record]: {} extends UnTagged<Record[T], TagProp> ? ((value?: {}) => TaggedRecord[keyof TaggedRecord]) : ((value: UnTagged<Record[T], TagProp>) => TaggedRecord[keyof TaggedRecord]);
+    [T in keyof Record]: ((value: UnTagged<Record[T], TagProp>) => TaggedRecord[keyof TaggedRecord]);
 };
```

The left hand side of the ternary is used because `{} extends { src?: string; className?: string }` resolves to `true`.

``` ts
// string
type Test = {} extends { src?: string; className?: string } ? string : number;
```

To try and understand why this condition was needed, I ran the Unionize tests and everything passed. 🤷‍♂ 

I then did a git blame and found:

- https://github.com/pelotom/unionize/commit/0e377c9dfef2f1041110c982e6570edcfdf9ae17
- https://github.com/pelotom/unionize/pull/31

@pelotom Do you have any ideas how we can satisfy both this issue and the one this ternary was originally added to fix (in https://github.com/pelotom/unionize/pull/31)?

It might also be worthwhile us adding some tests for this and the issue fixed by https://github.com/pelotom/unionize/pull/31.

**Comment by pelotom** [comment]
@OliverJAsh 

> @pelotom Do you have any ideas how we can satisfy both this issue and the one this ternary was originally added to fix (in #31)?

Seems like this would fix it?

```diff
export type Creators<Record, TaggedRecord, TagProp extends string> = {
-  [T in keyof Record]: {} extends UnTagged<Record[T], TagProp>
+  [T in keyof Record]: {} extends Required<UnTagged<Record[T], TagProp>>
    ? ((value?: {}) => TaggedRecord[keyof TaggedRecord])
    : ((value: UnTagged<Record[T], TagProp>) => TaggedRecord[keyof TaggedRecord])
};
```

> It might also be worthwhile for us to add some tests for this and the issue fixed by #31.

Yeah, there's a general need for type-level tests which allow expressing negative assertions (e.g. with [dtslint](https://github.com/microsoft/dtslint)) but I haven't gotten around to adding support for it.

**Comment by OliverJAsh** [comment]
Potential breaking change related to this fix:

``` ts
import unionize, { ofType } from 'unionize';

const MyUnion = unionize({ MyRecord: ofType<{ src?: string; }>() });

MyUnion.MyRecord(); // fine in 3.0.0, errors in 3.0.1
MyUnion.MyRecord({}); // workaround for 3.0.1
```

Should I file a new issue?

**Comment by pelotom** [comment]
Yeah, it’s a backwards breaking change and I probably should’ve revved a new major version. I don’t consider it a bug though.
