### ISSUE TITLE
Enumerate union

### ISSUE THREAD

**Issue by OliverJAsh** [pelotom/unionize#50]
I want to create a tuple of all my union's members.

To achieve this with unions elsewhere, I can do the following:

``` ts
type ExactMatch<Union, Arr> = Union[] extends Arr ? (Arr extends Union[] ? Arr : never) : never;
const enumerateUnion = <T extends unknown>() => <U extends unknown>(
  arg: ExactMatch<T, U>,
) => arg;
```

As recommended here: https://github.com/Microsoft/TypeScript/issues/13298#issuecomment-468733257

For example:

``` ts
enum Foo {
  bar,
  baz
}

// good
enumerateUnion<Foo>()([Foo.bar, Foo.baz])
// bad
enumerateUnion<Foo>()([Foo.bar])
```

However, when I tried to do this with a unionize union, I realised it's not possible because the constructors return the union rather than the (tagged) member that has been constructed:

``` ts
const Foo = unionize({
  bar: {},
  baz: {}
});

// good (should be bad!)
enumerateUnion<Foo>()([Foo.bar()])
```

Have you got any alternative ideas about how we could enumerate a unionize union? Alternatively, is there a way to make unionize union's work with the `enumerateUnion` I defined above?

**Comment by pelotom** [comment]
Unionize's constructors are just a convenience which allows you to leave off the tag, i.e.

`Foo.bar()` is the same as `{ tag: 'bar' }`, except that, as you noted, it purposely "forgets" the information about which variant it is, returning the union type. So to get this to work you can just write out the variants as raw objects:

```ts
const Foo = unionize({
  bar: {},
  baz: {}
});
type Foo = UnionOf<typeof Foo>;

// good
enumerateUnion<Foo>()([{ tag: 'bar' }, { tag: 'baz' }]);
// bad
enumerateUnion<Foo>()([{ tag: 'bar' }]);
```

**Comment by OliverJAsh** [comment]
Thanks!
