### ISSUE TITLE
Circular definition issue

### ISSUE THREAD

**Issue by sledorze** [pelotom/unionize#6]
```typescript
const def = unionize({
  or: ofType<{ a: Def, b: Def }>()
})

type Def = typeof def._Union // Error: Type alias 'Def' circularly references itself
```
One cannot create a recursive Union.

**Comment by pelotom** [comment]
As with #4, this may be a fundamental limitation of the approach. Any ideas for getting around it?

**Comment by sledorze** [comment]
@pelotom I think we should define first the (target) Union type (so that we can define it recursively) and then call unionize specifying both that type AND pass the required (value level) keys in order to be able to generate the code.

**Comment by sledorze** [comment]
Something like this would provider enough information

```typescript
type Def = {
  or: { a:  Def, b:  Def  }
}

const def = unionize<Def>({ or })
```

**Comment by pelotom** [comment]
I'm really not sure what you're proposing exactly. First of all the example you're using is weird because it creates an infinite type; `Def` can never be instantiated. Maybe it would be better to translate this example into a more recognizable but still simple recursive type like `Nat`. Second of all this seems wrong:

```ts
type Def = {
  or: { a:  Def, b:  Def  }
}
```

because the inner fields `a` and `b` should not be of type `Def` but rather `typeof unionize<Def>({ or: any })._Union`*, no?

* pretending that `typeof` works on arbitrary expressions, of course.

**Comment by sledorze** [comment]
@pelotom 
The example was shrinked, so yes, completely infinite and not instantiable, just to get the gist of the problem.

Your second remark is correct, my example is completely wrong.
I'm now unsure it could be done at all.

**Comment by sledorze** [comment]
@pelotom a possible solution would be to define beforeHand all types and their relations (event cyclic)
and then, from them, to generate the runtime values.
We completely loss the rad aspect of the library but it should works

**Comment by sledorze** [comment]
@pelotom here's an example (that's not pretty) maybe worth adding those helpers..

```typescript
type Rec<O> = {[k in keyof O]: { tag: k } & O[k]}[keyof O]
const recursive = <O, Res = {[k in keyof O]: O[k]}>(o: {[k in keyof O]: undefined }): Res => {
  const res = {} as Res
  for (const k in o) {
    if (o.hasOwnProperty(k)) {
      (<any>res)[k] = undefined
    }
  }
  return res
}

type Query = {
  providerQuery: { provider: string, queryParam: number }
  unionQuery: { queries: Rec<Query>[] }
}

const queryUnion =
  unionize(recursive<Query>({
    providerQuery: undefined,
    unionQuery: undefined
  }))
```

Note: 'tag' is hardcoded here and may need to be parametrized, on need..

**Comment by sledorze** [comment]
Additionally you may refer to part of the other entries like so:

```typescript
type Variant<Q, P extends keyof Q> = { tag: P } & Q[P]
type OfQuery<P extends keyof Query> = Variant<Query, P>

type Query = {
  provider: { name: string },
  intersection: { queries: Rec<Query>[] },
  anotherQuery: { provider: OfQuery<'provider' |  'intersection'> },
}
```

**Comment by pelotom** [comment]
The type system doesn't seem to be able to handle this:

```ts
typeof queryUnion._Union = ({
    tag: "providerQuery";
} & {
    provider: string;
    queryParam: number;
}) | ({
    tag: "unionQuery";
} & {
    queries: (({
        tag: "providerQuery" | "unionQuery";
    } & {
        provider: string;
        queryParam: number;
    }) | ({
        tag: "providerQuery" | "unionQuery";
    } & any))[];
})
```

Note that the type of the array elements of `queries`, which should be equivalent to the whole union type, is wrong:

```ts
{
  tag: "providerQuery" | "unionQuery";
} & {
  provider: string;
  queryParam: number;
}) | ({
  tag: "providerQuery" | "unionQuery";
} & any
```

**Comment by sledorze** [comment]
@pelotom that's strange, I don't have the same inference..

**Comment by sledorze** [comment]
The any part is due to the type recursion.
Note that I have a correct inference.
but that may be due to me using Typescript version 2.6.0-dev.20170906 which may explain it.



```typescript
(property) is: {
    providerQuery: (variant: ({
        tag: "providerQuery";
    } & {
        provider: string;
        queryParam: number;
    }) | ({
        tag: "unionQuery";
    } & {
        queries: (({
            tag: "providerQuery";
        } & {
            provider: string;
            queryParam: number;
        }) | ({
            tag: "unionQuery";
        } & any))[];
    })) => variant is {
        tag: "providerQuery";
    } & {
        provider: string;
        queryParam: number;
    };

```

**Comment by sledorze** [comment]
Ok @pelotom I've reproduced your issue going back to version 2.5.2.
From the definition of Rec, I expect the behaviour exhibited by the newer version to be correct.
Well, so it may be interesting in the (not so far) future..

**Comment by pelotom** [comment]
Are you saying it works in `typescript@next`?

**Comment by sledorze** [comment]
For a definition of next, yes! :)

**Comment by pelotom** [comment]
Ah, I missed your first comment about it working in `typescript@2.6.0-dev.20170906`. Yes, that's `typescript@next` 🙂

**Comment by sledorze** [comment]
note: if one combines a lot of Rec<..> into an union, the compiler goes crazy as there could be a lot of path to discover before identifying a structural recursion.
Meaning, it terminates but generates a Huge tree in memory; note that this has nothing to do with the technique but is a general compiler issue.

**Comment by pelotom** [comment]
Sounds like something to file a TS bug on!

**Comment by sledorze** [comment]
Oh no actually, this has to do with the technique and definition of Rec.

**Comment by sledorze** [comment]
Yes I'm on it!

**Comment by sledorze** [comment]
@pelotom in fact that looks completely legitimate, I'm recreating a new type (even if structurally equivalent) - need to find another way, that one has an exponential issue.

**Comment by sledorze** [comment]
@pelotom I've tried several paths; they all lead to 'type massage' (add tag / flatten values) + 'recursion' = exponential issue.

**Comment by sledorze** [comment]
@pelotom I've found an issue with the compiler actually:
https://github.com/Microsoft/TypeScript/issues/18754

**Comment by sledorze** [comment]
@pelotom for your information, I've decided to implement another solution as I've got a few design decisions that are not compatibles with the current implementation of unionize.

Main points of divergence is:
- Support self recursive sum types.
- When doing the previous point, do not generate combinatorial complexity of union types at the compiler level.

To achieve this, I am relying on interfaces (to stop the compiler inference during union expansions).
So the result a lot more verbose than unionize.

```typescript

interface Foo {
    name: string
}
interface Bar {
    provider: All,
    params: number
}

interface Baz {
    queries: All[]
}

const query =
    sumize({
        foo: ofType<Foo>(),
        bar: ofType<Bar>(),
        baz: ofType<Baz>()
    })

type All = typeof query.sumType
```

**Comment by pelotom** [comment]
I'm confused by your example, isn't `unionize` capable of doing that as-is?

```ts
interface Foo {
  name: string
}

interface Bar {
  provider: All,
  params: number
}

interface Baz {
  queries: All[]
}

const query =
  unionize({
      foo: ofType<Foo>(),
      bar: ofType<Bar>(),
      baz: ofType<Baz>()
  })

type All = typeof query._Union
```

**Comment by sledorze** [comment]
Oh! believe it or not but I've been full circle trying alternative to find a way to fixe that combinatorial issue (still trying to mimick the actual unionize API).

I think in the end, yes, unionize is completely able to express circular references.

the differences I have with it are these (and have no more to do with recursion) :
- More precise type by default (variant type at construction instead of union one).
- Expose the actual required members of the instance in constructors (otherwise, the developper have to look at interfaces definitions which are opaques).

Besides that it's the same feature set.
