### ISSUE TITLE
More precise typing of variants.

### ISSUE THREAD

**Issue by sledorze** [pelotom/unionize#7]
When instantiating one variant of a union, it is typed as the type of the union.
It would be nicer to have the actual narrower type of the variant.

To achieve this, one could change the signature of Creators from
```typescript
export type Creators<Record, TaggedRecord> = {
  [T in keyof Record]: (value: Record[T]) => TaggedRecord[keyof TaggedRecord]
}
```

to

```typescript
export type Creators<Record, TaggedRecord> = {
  [T in (keyof Record & keyof TaggedRecord)]: (value: Record[T]) => TaggedRecord[T]
}
```

any chance to get that in?

**Comment by pelotom** [comment]
At one point I was doing this because it seemed to help type inference in certain cases, but I'm not sure if it really helped. Feel free to submit a PR for this and I'll see if it causes problems in my private repo.

**Comment by sledorze** [comment]
Which version of TS is your project using?

**Comment by pelotom** [comment]
I just saw your question. It's currently on [`2.4.2`](https://github.com/pelotom/unionize/blob/master/package.json#L20)

**Comment by sledorze** [comment]
Me too, a lot of progress in caching has been made, it helps a lot with OOM issues :)

**Comment by sledorze** [comment]
Closing as I think it's a design choice.
